holos-run/holos

.cspell.json, doc/md/guides/expose-a-service.mdx, internal/generate/components/v1alpha3/httpbin-workload/components/httpbin/workload/httpbin-workload.cue, internal/generate/components/v1alpha3/httpbin-workload/httpbin-workload.gen.cue, internal/generate/components/v1alpha3/httpbin-workload/schematic.json, internal/generate/components/v1alpha3/referencegrant/referencegrant.gen.cue, internal/generate/components/v1alpha3/referencegrant/schematic.json, internal/generate/platforms/cue.mod/pkg/github.com/holos-run/holos/api/schema/v1alpha3/definitions.cue
This patch manages the httpbin Deployment, Service, and ReferenceGrant.
The remaining final step is to expose the service with an HTTPRoute and
Certificate.
We again needed to add a field to the schema APIObjects to get this to
work.  We need to fix #237 soon.  We'll need to do it again for the
HTTPRoute and Certificate resources.
=> docs: add httpbin workload section to expose a service

api/schema/v1alpha3/definitions.go, doc/md/api/schema/v1alpha3.md, doc/md/guides/expose-a-service.mdx, internal/generate/components/v1alpha3/httpbin-routes/components/httpbin/routes/httpbin-routes.cue, internal/generate/components/v1alpha3/httpbin-routes/httpbin-routes.gen.cue, internal/generate/components/v1alpha3/httpbin-routes/schematic.json, internal/generate/platforms/cue.mod/gen/github.com/holos-run/holos/api/schema/v1alpha3/definitions_go_gen.cue, internal/generate/platforms/cue.mod/pkg/github.com/holos-run/holos/api/schema/v1alpha3/definitions.cue
This patch adds the httpbin routes component.  It's missing the
Certificate component, the next step is to wire up automatic certificate
management in the gateway configuration, which is a prime use case for
holos.  Similar to how we register components and namespaces, we'll
register certificates.
This patch also adds the #Platform.Domain field to the user facing
schema API.  We previously stored the domain in the Model but it makes
sense to lift it up to the Platform and have a sensible default value
for it.
Another example of #237 needing to be addressed soon.
Closes: #234
=> docs: add httpbin routes section to expose a service guide

doc/website/docusaurus.config.ts, doc/website/src/components/HomepageFeatures/index.tsx, doc/website/src/css/custom.css, doc/website/src/pages/index.tsx
PROBLEM:
The landing page contains a lot of text, and much of that text was
written before we refined our messaging within the guides and technical
overview pages.
SOLUTION:
* Whittle down landing page text to only the key messages we want to convey.
* Provide messaging bullets for the features.
* Steer folks (via links) to the quickstart guide or technical overview document.
OUTCOME:
Visitors don't need to wade through a lot of text to receive key
messaging talking points or links to the pages they should read.
=> Make the landing page more concise

api/core/v1alpha4/types.go, doc/md/api/core/v1alpha4.md, internal/builder/v1alpha4/builder.go, internal/generate/platforms/cue.mod/gen/github.com/holos-run/holos/api/core/v1alpha4/types_go_gen.cue
Previously the Artifact collection was processed sequentially.  This
patch provides a modest performance improvement, about 16% faster for
our simple 2 artifact use case, by processing each artifact
concurrently.
=> v1alpha4: add concurrent build plan artifacts

api/core/v1alpha4/types.go, doc/md/api/core/v1alpha4.md, holos.go, internal/artifact/artifact.go, internal/builder/v1alpha4/builder.go, internal/generate/platforms/cue.mod/gen/github.com/holos-run/holos/api/core/v1alpha4/types_go_gen.cue, internal/generate/platforms/cue.mod/pkg/github.com/holos-run/holos/api/core/v1alpha4/types.cue
The Join transformer was not implemented.  This patch completes the transformers we support, the Join and Kustomize transformers.
- **artifact: add Save() method to save artifacts**
- **v1alpha4: add Join transformer**
=> v1alpha4: add join transformer

api/core/v1alpha4/types.go, doc/md/api/core/v1alpha4.md, internal/builder/v1alpha4/builder.go, internal/generate/platforms/cue.mod/gen/github.com/holos-run/holos/api/core/v1alpha4/types_go_gen.cue
Previously helm charts were cached only by name, which is a problem
because the wrong version would be used when previously cached.
This patch caches charts by name and version to ensure changes in the
version results in pulling the new cached version.  It is the user's
responsibility to remove old versions.
This patch also ensures only a single go routine can run cacheChart() at
a time across processes.  This is necessary when rendering a platform
because multiple processes will run the Helm generator concurrently, for
example when the same chart is used for multiple environments or
customers.
The mkdir system call serves as the locking mechanism, which is robust
and atomic on all commonly used file systems.
=> v1alpha4: cache helm charts by version (#273)

doc/md/guides/deploy-a-service.mdx
PROBLEM:
Version v1alpha4 of the Author API has been updated with backwards
incompatible changes, and the deploy-a-service guide uses code from
version v1alpha3.
SOLUTION:
Update any code, links, and data that is out of date, and then run
through the guide to make sure it works locally.
OUTCOME:
The instructions in the deploy-a-service guide will work successfully
with version v1alpha4 of the Author API.
=> Update deploy-a-service guide for Author API v1alpha4

cmd/holos/tests/v1alpha5/guides/helm.txt, holos.go, internal/builder/v1alpha5/builder.go, internal/cli/render/render.go, internal/generate/platforms/v1alpha5/platform/platform.gen.cue
Previously the holos command line expected a Platform and BuildPlan resource at the top level of the exported data from CUE.  This forced us to use hidden fields for everything else.
This patch modifies the BuildData struct to first look for a holos top level field and use it if present.  This opens up other top level fields for use by end users.
Our intent is to reserve any top level field prefixed with holos.
Note this follows how Timoni works as well.
Closes: #308
=> render: nest output under the holos top level field (#308)

doc/md/diagrams/render-component-sequence.mdx, doc/md/diagrams/render-platform-sequence.mdx, doc/md/diagrams/rendering-overview.mdx, doc/md/tutorial/1-overview.mdx
Attribution: following the structure and length of the tokio docs, with
some more diagrams.
=> docs: rewrite technical overview for v1alpha5

cmd/holos/tests/cli/first-impression.txt, internal/cli/root.go
Fixes:
```
❯ holos
panic: runtime error: slice bounds out of range [2:1]
goroutine 1 [running]:
github.com/holos-run/holos/internal/cli.newCueCmd(...)
/home/mike/go/pkg/mod/github.com/holos-run/holos@v0.98.1/internal/cli/root.go:121
github.com/holos-run/holos/internal/cli.New(0xc0002837c0, {0x3826e00, 0x4f60860})
/home/mike/go/pkg/mod/github.com/holos-run/holos@v0.98.1/internal/cli/root.go:102 +0x772
main.main.MakeMain.func1()
/home/mike/go/pkg/mod/github.com/holos-run/holos@v0.98.1/internal/cli/main.go:22 +0x5b
main.main()
/home/mike/go/pkg/mod/github.com/holos-run/holos@v0.98.1/cmd/holos/main.go:10 +0x3e
```
Closes: #334
=> cue: fix panic with no args (#334)

.cspell.json, api/author/v1alpha5/definitions.go, api/core/v1alpha5/types.go, cmd/holos/tests/v1alpha5/schemas/capabilities.txt, doc/md/api/author.md, doc/md/api/core.md, internal/builder/v1alpha5/builder.go, internal/cli/render/render.go, internal/generate/platforms/cue.mod/gen/github.com/holos-run/holos/api/author/v1alpha5/definitions_go_gen.cue, internal/generate/platforms/cue.mod/gen/github.com/holos-run/holos/api/core/v1alpha5/types_go_gen.cue, internal/generate/platforms/cue.mod/pkg/github.com/holos-run/holos/api/author/v1alpha5/definitions.cue
Previously the Helm generator had no support for the --api-versions flags.  This is a problem for helm charts that conditionally render resources based on this capability.
This patch plumbs support through the author and core schemas with a new field similar to how the enable hooks field is handled.
Closes: #330
=> helm: add support for helm template --api-versions capabilities (#330)

doc/md/topics/argocd-application.mdx
When we moved from v1alpha4 to v1alpha5 we removed ArgoConfig from the author schema.  There was no longer a clear example of how to configure an ArgoCD Application for every component in v1alpha5.
This patch adds a topic document with an example of how to add an Application along side the resources by mixing an additional Artifact into the BuildPlan.
Closes: #340
=> docs: add argocd application example (#340)

doc/website/static/_redirects
PROBLEM:
See #350 for context. There's a GitHub issue open for this on the
facebook docusaurus repo:
https://github.com/facebook/docusaurus/issues/9049
SOLUTION:
Use the redirect workaround for the time being.
OUTCOME:
https://holos.run/docs will link to the most recent version of our docs
site.
=> Redirect docs to current version

cmd/holos/tests/cli/cue-vet.txt, internal/cli/root.go
Without this patch `holos cue vet` always returns exit code 0, even when
there are errors.
This patch fixes the problem by catching the error and returning it to
our own top level error handler.  Note the final error, "could not run:
terminating because of errors" which wraps the generic error reported by
cue in the presence of multiple errors.
Result:
```
❯ holos cue vet ./policy --path 'strings.ToLower(kind)' /tmp/podinfo.gen.yaml
deployment.kind: conflicting values "Forbidden" and "Deployment":
./policy/validations.cue:18:8
../../../../../tmp/podinfo.gen.yaml:25:7
deployment.spec.template.spec.containers.0.resources.limits: conflicting values null and {[string]:"k8s.io/apimachinery/pkg/api/resource".#Quantity} (mismatched types null and struct): …
```
=> cue: fix holos cue vet exit code (#358)

cmd/holos/tests/v1alpha5/issues/issue366-cue-build-tags.txt, internal/cli/render/render.go, internal/holos/types.go
Previously Holos only supported tags in the form of key=value.  CUE supports boolean style tags in the form of `key [ "=" value ]` which we want to use to conditionally use to register components with the platform.
This patch modifies the flag parsing to support -t foo like cue does, for use with the @if(foo) build tag.
Closes: #366
=> render: support cue build tags e.g. -t foo for @if(foo) (#366)

internal/builder/platform.go, internal/cli/render/render.go, internal/cli/show.go, internal/holos/types.go, internal/util/run.go
Previously, build tags were not propagated from `holos render platform -t validate` through to the underlying `holos render component` command. This is a problem because validators need to be selectively enabled as a work around until we have an audit mode field.
This patch fixes the problem by propagating command line tags from the render platform command to the underlying commands.  This patch also propagates tags for the show command.
Closes: #366
=> render: pass build tags from platform to component (#366)

doc/md/tutorial/helm-values.mdx, doc/md/tutorial/overview.mdx, doc/website/src/components/YouTube/index.tsx, doc/website/src/components/YouTube/styles.module.css
PROBLEM:
We've created a YouTube video walking people through Holos and the Helm
Values tutorial, but now we need to embed it on the site for visitors to
watch.
SOLUTION:
* Create a `YouTube` MDX plugin
* Use that plugin on Overview and Helm Values
* Tune the video size/attributes using CSS
OUTCOME:
The Helm Values YouTube video is embedded on our site for visitors to
watch.
=> Embed YouTube Video

doc/md/topics/comparison.mdx
PROBLEM:
We've noticed that Holos almost immediately gets compared to Timoni, and
we frequently get asked for specifics in how they're similar/different.
SOLUTION:
* Add a `Comparison` page.
* Include a section that compares Holos to Timoni
OUTCOME:
Fewer questions about how Holos compares to Timoni because people are
able to find that answer themselves on our docs page.
=> Add a Comparisons page

api/author/v1alpha5/definitions.go, api/core/v1alpha5/types.go, doc/md/api/author.md, doc/md/api/core.md, internal/builder/v1alpha5/builder.go, internal/generate/platforms/cue.mod/gen/github.com/holos-run/holos/api/author/v1alpha5/definitions_go_gen.cue, internal/generate/platforms/cue.mod/gen/github.com/holos-run/holos/api/core/v1alpha5/types_go_gen.cue, internal/generate/platforms/cue.mod/pkg/github.com/holos-run/holos/api/author/v1alpha5/definitions.cue
Without this patch migrating from [helm hierarchies] to Holos requires the user to unify the value hierarchy.  This is a problem because helm hierarchies are difficult to unify because it's not clear if or why a value is used in the final results.  This makes it difficult to identify how to resolve conflicts.
This patch adds `valueFiles` field to the Helm component kind.  This field is intended to provide a direct migration path from the ApplicationSet.spec.template.spec.sources.helm.valueFiles field.  With this patch, users can directly migrate the values files to CUE using `@embed`, then directly migrate the valueFiles field to reference the values from within CUE.
Note we actively discourage the use of Helm value hierarchies.  The feature is intended as a temporary migration tool.  We …
=> helm: add valueFiles for migration from an ApplicationSet

doc/md/tutorial/setup.mdx
- Updates the tested Helm version to v3.17.3 in the setup documentation.
- Adds a "Known Issues" section to the setup documentation.
- Notes that Helm v3.18.0 produces incorrect output and links to the relevant Holos and Nixpkgs issues.
Fixes #433
=> docs: Update Helm version and add known issue

api/core/v1alpha6/types.go, internal/helm/helm.go
Currently Holos does not support authentication for OCI charts, just for Helm charts.
This is because for OCI charts, the registry (host name of the chart ref) has to be authenticated before the Pull operation. This problem can be recreated using the Helm CLI directly, it's a limitation of it and not of Holos.
This changes ensure that when a OCI reference is passed and there is user and password, the authentication is done on the registry client before doing the pull.
=> Allows authentication of OCI charts
